project_name: kots2helm
release:
  github:
    owner: replicatedhq
    name: kots2helm
builds:
  - id: kots2helm
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/kots2helm/main.go
    ldflags: -s -w
      -X github.com/replicatedhq/kots2helm/pkg/version.version={{.Version}}
      -X github.com/replicatedhq/kots2helm/pkg/version.gitSHA={{.Commit}}
      -X github.com/replicatedhq/kots2helm/pkg/version.buildTime={{.Date}}
      -extldflags "-static"
    flags: -tags netgo -installsuffix netgo
    binary: kots2helm
    hooks: {}
archives:
  - id: kots2helm
    builds:
      - kots2helm
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    files:
      - licence*
      - LICENCE*
      - license*
      - LICENSE*
      - readme*
      - README*
      - changelog*
      - CHANGELOG*
